name: GraalVM Native Image builds
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: HelloWorld on windows-latest
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./example-project
    steps:
      - uses: actions/checkout@v4

      - uses: jessiscript/setup-graalvm@main
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build and run exampleProject
        run: |
          mvn -Pnative package
          .\target\example-project-0.0.1-SNAPSHOT example-project


      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-windows-latest
          path: example-project*