name: GraalVM Native Image builds
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: HelloWorld on windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jessiscript/setup-graalvm@main
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'

      - name: Build and run exampleProject
        working-directory: ./example-project
        run: mvn -Pnative package


      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-windows-latest
          path: helloworld*