name: GraalVM Native Image builds
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: HelloWorld on windows-latest
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./game-of-life-native
    steps:
      - uses: actions/checkout@v4

      - uses: jessiscript/setup-graalvm@main
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pat-token: ${{ secrets.TOKEN }}
          native-image-job-reports: 'true'
          native-image-metric-history: 'true'
          build-counts-for-metric-history: '10'
          native-image-pr-comparison: 'true'
          native-image-pr-reports: 'true'
      - name: Example step
        run: |
          echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
          javac HelloWorld.java
          native-image HelloWorld
          ./helloworld

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-${{ matrix.os }}
          path: helloworld*
